### ISSUE TITLE
Retain the searched terms in the search bar after the query launches 

### ISSUE THREAD

**Issue by dani-ajah** [ajah/sks-interface#5]
As a user of the platform, I want to be able to see the search terms I selected on the search bar after launching a query, so that I can easily edit my search once I see the results.

**Comment by dani-ajah** [comment]
Ensure that when typing a keyword, pressing the enter key and the search button have the same behaviour of inputting the keyword and creating a tile with the keyword above the search bar.

Deleting the keywords from the search bar once it is made into a tile.

**Comment by dani-ajah** [comment]
Currently, if a user conducts a search from the home page and hits enter or clicks the search button they are redirected to the search page, however, their initial keyword is not shown above the search bar. Could we allow it to be saved like when they enter a keyword straight from the search page?

**Comment by dani-ajah** [comment]
@hjweinreb Is the limit on 3 words something that can be fixed? Could a user potentially search for more than 3?

**Comment by hjweinreb** [comment]
> Currently, if a user conducts a search from the home page and hits enter or clicks the search button they are redirected to the search page, however, their initial keyword is not shown above the search bar. Could we allow it to be saved like when they enter a keyword straight from the search page?

Yes! I am working on this. It's a little tricky but I will do it.





> @hjweinreb Is the limit on 3 words something that can be fixed? Could a user potentially search for more than 3?

Definitely. I think we should have a cap though. What number are you thinking? 10?

**Comment by gustavohandrade** [comment]
We need to retain only the last terms searched. Currently, the hub retains all terms previously searched.

**Comment by hjweinreb** [comment]
> We need to retain only the last terms searched. Currently, the hub keeps all terms previously searched.
> 
> ![Image](https://user-images.githubusercontent.com/106772124/183954481-6e1bb878-294f-46cf-a41b-16890c7b83f6.png)

Hey @gustavohandrade , Not sure I understand. The user can remove any of the search terms using the X button. Also refreshing the page does a total reset on the search terms.

**Comment by psdcode** [comment]
### 2hrs or 3hrs

In terms of how the url addresses are used in general on the web, refreshing a page with query terms and filters in the address bar, should utilize those terms and filters and not do a reset. If you do a total reset when you refresh, then linking to a specific search result (eg, from an external site) is not possible.

As in issues https://github.com/ajah/sks-interface/issues/30 and https://github.com/ajah/sks-interface/issues/34 problem is we are not syncing the address bar query params state with the application's search context variables that are meant to correspond to these params. Query params should take priority.

Some related issues:
- When on the home page, entering more than one word separated by a space treats it as a single term when redirect to search page. Should be two separate tiles:
  - ![Image](https://user-images.githubusercontent.com/10729355/184798897-77f7735a-8d29-4103-a7aa-19dacba345d5.png)

- It is not possible to delete the final remaining tile 
  - ![Image](https://user-images.githubusercontent.com/10729355/184800361-cb0cc451-db45-47e2-b310-e8e21ab76065.gif)

**Comment by psdcode** [comment]
Hi @hjweinreb. In terms of how the url addresses are used in general on the web, refreshing a page with query terms and filters in the address bar, should utilize those terms and filters and not do a reset. If you do a total reset when you refresh, then linking to a specific search result (eg, from an external site) is not possible. Unless I'm mistaken and there was a specific request to do it this way.

As in issues https://github.com/ajah/sks-interface/issues/30 and https://github.com/ajah/sks-interface/issues/34, the problem is we are not syncing the address bar query params state with the application's search context variables that are meant to correspond to these params. It seems to me query params should take priority.

@dani-ajah @gustavohandrade I'm not sure

**Comment by psdcode** [comment]
Hi @hjweinreb. In terms of how the url addresses are used in general on the web, refreshing a page with query terms and filters in the address bar, should utilize those terms and filters and not do a reset. If you do a total reset when you refresh, then linking to a specific search result (eg, from an external site) is not possible. Unless I'm mistaken and there was a specific request to do it this way.

As in issues https://github.com/ajah/sks-interface/issues/30 and https://github.com/ajah/sks-interface/issues/34, the problem is we are not syncing the address bar query params state with the application's search context variables that are meant to correspond to these params. It seems to me query params should take priority.
